### ISSUE TITLE
Buying stuck

### ISSUE THREAD

**Issue by Legendjson2** [OvernodeProjets/Heliactyl-fixed#11]
When someone tries to buy resources it stuck and keeps loading then shows 504 gateway time-out .
i am attaching a image below .
![Screenshot 2024-04-21 191203](https://github.com/OvernodeProjets/Fixed-Heliactyl/assets/108113574/350efcd1-31cb-49f7-baef-6d355141bf8c)

**Comment by achul123** [comment]
[Fix](https://github.com/OvernodeProjets/Fixed-Heliactyl/commit/0e4cdf69c97b1820c76fc99d2eebea9f435cd15e)
