### ISSUE TITLE
Renew Issue 

### ISSUE THREAD

**Issue by Legendjson2** [OvernodeProjets/Heliactyl-fixed#12]
After doing renew one time it shows **not renewable** for reference check the image . 
![Screenshot 2024-04-22 145622](https://github.com/OvernodeProjets/Fixed-Heliactyl/assets/108113574/3e212240-e291-4613-9995-4ccadadb927d)

**Comment by KingTino104** [comment]
"It's not advisable to use the renewals system, as it's unstable and doesn't work all the time."
