### ISSUE TITLE
It doesn't work in the new update; the following error appears.

### ISSUE THREAD

**Issue by PancaDevGIT** [OvernodeProjets/Heliactyl-fixed#20]
![Captura de pantalla 2024-05-29 142845](https://github.com/OvernodeProjets/Fixed-Heliactyl/assets/87989063/825fd342-2b20-4bf0-b910-88f06643147f)

**Comment by achul123** [comment]
When did you get this? When you launched the node or when you went to a page?

**Comment by PancaDevGIT** [comment]
When I went to a page

**Comment by achul123** [comment]
Maybe because you didn't do the installation properly, because everything works perfectly for me.
