### ISSUE TITLE
Branding issue

### ISSUE THREAD

**Issue by ethzr** [OvernodeProjets/Heliactyl-fixed#7]
I'm the developer of Heliactyl before it went EOL and I just want to say that we don't allow forks to have names that imply they the official / latest version of Heliactyl - that would include "Heliactyl-fixed"

Please use a name such as "BetterHeliactyl", or anything that has a word before it
You should also state that it is a fork of Heliactyl v12 and not official

Thank you

**Comment by ethzr** [comment]
Also, if you'd like the latest patches for v12/v14, add me on discord (username is atqr)

**Comment by achul123** [comment]
This is not stated in your licenses, and forks have every right to the licenses if they are the main creators.

**Comment by ethzr** [comment]
> This is not stated in your licenses, and forks have every right to the licenses if they are the main creators.

We try and enforce some basic rules on forks (and have since 2022), this is to prevent unofficial Heliactyl forks from being shown over the official (but EOL) Heliactyl

**Comment by achul123** [comment]
Accept me on discord we'll discuss this tomorrow (achul123)
